import Head from 'next/head'
import styles from '../styles/Ada4AllApps.module.css'
import ButtonMenu from '../components/ButtonMenu'
import SliderCards from '../components/SliderCards';

export default function Ada4AllApps() {

    return (
        <div >
            <Head>
                <title> Ada 4 All </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="backgroundWrapper">
                <video className="videoBackground"
                    src="videos/video_background.mp4"
                    type="video/mp4"
                    autoPlay
                    muted
                    loop>
                </video>
            </section >

            <main className={styles.container}>
                <SliderCards/>
            </main>
            
            <ButtonMenu />
        </div>
    )
}






