import Head from 'next/head'
import styles from '../styles/Contato.module.css'
import ButtonMenu from '../components/ButtonMenu'
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import SocialMedia from '../components/SocialMedia';

export default function Contato() {

    return (
        <div >
            <Head>
                <title> Contato </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="backgroundWrapper">
                <video className="videoBackground"
                    src="videos/video_background.mp4"
                    type="video/mp4"
                    autoPlay
                    muted
                    loop>
                </video>
            </section >

            <main className={styles.main}>
                <section className={styles.about}>
                    <h3 className={styles.title}> <ChevronRightIcon /> ADA na midia </h3>
                    <iframe 
                        src="https://www.youtube.com/embed/OYyQxrYsaUY" title="YouTube video player" 
                        frameborder="0" 
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                        allowfullscreen>
                    </iframe>
                </section>      

                <SocialMedia/>     
            </main>

            <ButtonMenu />
        </div>
    )
}






