import Head from 'next/head'
import ButtonMenu from '../components/ButtonMenu'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title> Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapperTitle}>
          <h1 className={styles.title}> Ada </h1>
        </div>
        <video className={styles.videoBackground} 
                src="videos/video_background.mp4"
                type="video/mp4"
                autoPlay
                muted
                loop>
        </video>
     
        <ButtonMenu/>
      </main>
    </div>
  )
}
