import Head from 'next/head'
import ButtonMenu from '../components/ButtonMenu'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title> Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Background </h1>
        <ButtonMenu/>
      </main>
    </div>
  )
}
