import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/QuemSomos.module.css'
import ButtonMenu from '../components/ButtonMenu'
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import team from '../api/members.json'

export default function QuemSomos() {
    return (
        <div >
            <Head>
                <title> Quem Somos </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className={styles.about}>
                    <h1 className={styles.title}> <ChevronRightIcon/> Por que Ada?  </h1>

                    <div className={styles.container}>
                        <div className={styles.description}>
                            <p> 
                                Fundada por duas mulheres jovens, negras, nordestinas e cientistas. A <strong> Ada </strong> tem como missão tornar o Metaverso uma realidade, conectando o mundo real com o virtual. 
                            </p>
                            <p>
                                Para isso, o time Ada, formado por Pesquisadores, Engenheiros, Neuroengenheiros, Neurocientistas, Desenvolvedores de games e Programadores, visa integrar as tecnologias de Realidade Virtual (VR), Realidade Aumentada (AR) e Internet das Coisas (IoT), possibilitando experiências imersivas e feedbacks sensoriais no Metaverso. 
                            </p>
                            <p>
                                Através dos projetos de inovação e desenvolvimento tecnológico da Ada, as tecnologias imersivas se tornarão mais acessíveis à população, pois a startup tem como meta fornecer experiências XR para todos. 
                            </p>
                        </div>

                        <img src='/images/ada_lovelace.jpg' 
                            className={styles.image}
                            title='Ada Lovelace' 
                            alt='Ada Lovelace'/>
                    </div>

                </section>

                <section className={styles.team}>
                    <h3 className={styles.title}> <ChevronRightIcon/> Nosso time </h3>
                    
                    <div className={styles.wrapperProfiles}>
                        {team.map(item => (
                            <div className={styles.cardProfile} key={item.id}>
                                <div className={styles.background}>
                                    <Image className={styles.imgLogo} 
                                           src={item.logo} 
                                           alt="Ada"
                                           width="500px"
                                           height="350px"/>
                                </div>
                                <img className={styles.imgProfile} src={item.imgprofile} alt={item.name}/>
                                <p className={styles.name}> {item.name} </p>
                                <p className={styles.role}> {item.function} </p>
                            </div>
                        ))}
                    </div>
                </section>
            </main>

            <ButtonMenu />
        </div>
    )
}






